# STORAGE
# Storage types:
#   yaml (default value)
#   sqlite (local file database)
#   mysql (change options below)
storage-type: yaml

mysql:
  host: localhost
  port: 3306
  database: hideplayer
  username: root
  password: ""


# Item
item:
  enable: true
  slot: 6
  show:
    material: LIME_DYE
    name: "&7Players: &aVisible &7(Right-Click)"
    lore: "&7Right-Click to toggle player visibility!"
  hide:
    material: GRAY_DYE
    name: "&7Players: &cHidden &7(Right-Click)"
    lore: "&7Right-Click to toggle player visibility!"

# Other
use-visible-status-on-join: true
cooldown: 3 #In second