# Item
slot: 6
show:
  material: LIME_DYE
  name: "&7Players: &aVisible &7(Right-Click)"
  lore: "&7Right-Click to toggle player visibility!"
hide:
  material: GRAY_DYE
  name: "&7Players: &cHidden &7(Right-Click)"
  lore: "&7Right-Click to toggle player visibility!"

# Other
default-state-show: false
cooldown: 3 #In second