storage:
  # [DB type]
  # => mysql        | [Remote] Save the data into Mysql database
  # => mariadb      | [Remote] Save the data into MariaDB database
  # => postgresql   | [Remote] Save the data into PostgreSQL database
  # => sqlite       | [File] Save the data into SQLite database
  # => h2           | [File] Save the data into H2 database (default)
  # => yaml         | [File] Save the data info .yml file
  type: h2

  settings:

    # [Remote DB settings - MySQL / MariaDB / PostgreSQL]
    remote-db:
      host: localhost
      port: 3306
      database: hideplayer
      username: root
      password: ""

    # [SQLite settings] (need .db extension)
    sqlite: "hideplayer.db"

    # [H2 settings]
    h2: "hideplayer"


# Item
item:
  enable: true
  slot: 6
  show:
    material: LIME_DYE
    name: "&7Players: &aVisible &7(Right-Click)"
    lore: "&7Right-Click to toggle player visibility!"
  hide:
    material: GRAY_DYE
    name: "&7Players: &cHidden &7(Right-Click)"
    lore: "&7Right-Click to toggle player visibility!"

# Other
use-visible-status-on-join: true
cooldown: 3 #In second