name: HidePlayer
version: ${project.version}
main: me.luucka.hideplayer.HidePlayer
api-version: 1.17
authors: [ LuuckA ]
description: Hide and Show player
libraries:
  - com.zaxxer:HikariCP:4.0.3
  - com.h2database:h2:1.4.200
commands:
  hideplayer:
    description: Reload plugin
  hideall:
    description: Hideall
  showall:
    description: Showall
  keepvisible:
    description: Keepvisible
permissions:
  hideplayer.*:
    default: op
    children:
      hideplayer.reload: true
      hideplayer.cooldown: true
  hideplayer.reload:
    default: false
    description: Reload plugin
  hideplayer.cooldown:
    default: false
    description: Bypass cooldown